### ISSUE TITLE
New players do not have skin in server

### ISSUE THREAD

**Issue by Cougar** [benbaptist/minecraft-wrapper#160]
The method getSkinTexture() in proxy.py tries to load skin texture from Minecraft server using URL in sessionserver response. When new player haven't uploaded any skin and uses default one, the "SKIN" and "url" keys in texture dictionary are missing.

```
Traceback (most recent call last):
  File "/home/mc/minecraft-wrapper/src/web.py", line 442, in get
    self.write(json.dumps(self.handleAction(request)))
  File "/home/mc/minecraft-wrapper/src/web.py", line 183, in handleAction
    info = self.runAction(request)
  File "/home/mc/minecraft-wrapper/src/web.py", line 292, in runAction
    skin = self.wrapper.proxy.getSkinTexture(uuid)
  File "/home/mc/minecraft-wrapper/src/proxy.py", line 140, in getSkinTexture
    r = requests.get(skinBlob["textures"]["SKIN"]["url"])
KeyError: 'SKIN'
```

Here is how the minecraft session response looks like for new player:

```json
{
    "profileId": "fad7f7c77a964f4a9625e821f17abb9b",
    "profileName": "C0ugar",
    "textures": {},
    "timestamp": 1426449809587
}
```

textures for users who have changed their skin looks like this:

```json
    "textures": {
        "SKIN": {
            "url": "http://textures.minecraft.net/texture/c61c6c25f235f1fc2284b7b47cdc408fa751ef95581a26aaef24791163bdfee"
        }
    },
```

It should be checked if "SKIN" key is missing in skinBlob["textures"] and handle that somehow. Either
1. set skin to None in proxy.py, change web javascript code so that it does not try to decode payload of /action/get_player_skin response and show some other PNG.
2. create some default png file or hardcode its contents in base64 into the code
3. download or extract steve.png or alex.png file from minecraft.jar and use its content
4. point skin URL to some known location like http://hydra-media.cursecdn.com/minecraft.gamepedia.com/f/f2/Alex_skin.png (referred from http://minecraft.gamepedia.com/Skin)

I added the latter to the code (I can make pull request if it looks good fix) but IMHO it is not very good and elegant solution
```diff
--- a/src/proxy.py
+++ b/src/proxy.py
@@ -137,6 +137,9 @@ class Proxy:
                if uuid in self.skinTextures:
                        return self.skinTextures[uuid]
                skinBlob = json.loads(self.skins[uuid].decode("base64"))
+               if not "SKIN" in skinBlob["textures"]:
+                       skinBlob["textures"]["SKIN"] = {}
+                       skinBlob["textures"]["SKIN"]["url"] = "http://hydra-media.cursecdn.com/minecraft.gamepedia.com/f/f2/Alex_skin.png"
                r = requests.get(skinBlob["textures"]["SKIN"]["url"])
                self.skinTextures[uuid] = r.content.encode("base64")
                return self.skinTextures[uuid]
```

I don't know about copyright of steve.png or alex.png in minecraft.jar but most probably it is not allowed to bundle them in the wrapper package. So, the best options probably remain exctraction of minecraft.jar during first start or drawing some default icon ourselves. What do you think?

**Comment by Cougar** [comment]
This is the patch I'm using right now 073294f924981a863ba1aae48afb19fdb3914f3d

**Comment by suresttexas00** [comment]
when  does this run?  What happens if there is no skin?? 

I am polling my players about this, but I don'think this has happened on my server.

**Comment by Cougar** [comment]
I added some debug code to see it:

```patch
diff --git a/src/proxy.py b/src/proxy.py
index 2329799..a50e362 100644
--- a/src/proxy.py
+++ b/src/proxy.py
@@ -343,8 +345,9 @@ class Client: # handle client/game connection
                                h.update(sharedSecret)
                                h.update(self.publicKey)
                                serverId = self.packet.hexdigest(h)
+                               print "SessionServer request: https://sessionserver.mojang.com/session/minecraft/hasJoined?username=%s&serverId=%s" % (self.username, serverId)
                                r = requests.get("https://sessionserver.mojang.com/session/minecraft/hasJoined?username=%s&serverId=%s" % (self.username, serverId))
-#                              print "SessionServer response: %s" % r.text
+                               print "SessionServer response: %s" % r.text
                                
                                self.packet.sendCipher = encryption.AES128CFB8(sharedSecret)
                                self.packet.recvCipher = encryption.AES128CFB8(sharedSecret)
```

I purchased new Minecraft game 1-2 weeks ago and haven't changed its skin yet.. Other players I use are at least year old and all have skin changed and work fine.

The problem is not just missing skin but because of missing key, the python code throws exception and it makes web interface quite unusable. Web doesn't show this new user in user list and when there are also some other users, the user list is going to flicker. I have't look into JS code yet but I think it does not matter anyway and the data source (proxy.py) should be fixed ;-) The question still is, what to do with thise default players.

**Comment by suresttexas00** [comment]
OK, that's why I am not seeing this error - I turned off Web Module due to problems with it, like #130 for me ...

**Comment by Cougar** [comment]
Yes, this could be the reason. I also didn't see user list first. Then I changed getSkinTexture() to return None which gave me a flickering user list. With my latest patch everything works fine except I don't like much that it downloads skin from gamepedia wiki. Could you try the patch in 073294f924981a863ba1aae48afb19fdb3914f3d and let us know if it soles your problem #130 ?

**Comment by suresttexas00** [comment]
Your patch goes to the release and not the the dev version that I am using...  I will have to manually patch it first.  Ill let you know how it works.

**Comment by suresttexas00** [comment]
It does not solve my particular issues with the web interface.

**Comment by suresttexas00** [comment]
This is working fine.  Thanks for you help!

**Comment by benbaptist** [comment]
Is this still an issue?

**Comment by suresttexas00** [comment]
I don't use the web interface anymore.. at least not for a long time (bigger fish to fry).  I can open it as a separate issue later, if need be.  I suspect that with all the Web Interface work done; probably not an issue anymore.  The topic of the thread was the skin issue, so you can close this.

**Comment by benbaptist** [comment]
Ah, okay.
